server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=false

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.github.avec112

# Validate entity mappings against schema managed by Flyway.
spring.jpa.hibernate.ddl-auto=validate

# PostgreSQL (docker compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=spring
spring.datasource.password=spring
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=spring

# Flyway
spring.flyway.default-schema=spring
spring.flyway.schemas=spring
spring.flyway.create-schemas=true


# AI
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.1:8b
spring.ai.ollama.embedding.options.model=nomic-embed-text

# pgvector/RAG
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE