CREATE SCHEMA IF NOT EXISTS spring;

CREATE EXTENSION IF NOT EXISTS vector;

-- TASK
CREATE TABLE IF NOT EXISTS spring.task (
    task_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description VARCHAR(300) NOT NULL,
    creation_date TIMESTAMPTZ NOT NULL,
    due_date DATE
);

-- REPORT
CREATE TABLE IF NOT EXISTS spring.report (
     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     office_id VARCHAR(50) NOT NULL,
     title VARCHAR(255) NOT NULL,
     body TEXT NOT NULL
);